name: Setup Environment Variables

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Set up environment variables
        run: |
          # Create .env.local file
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" > .env.local
          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL || 'https://your-deployed-app-url.com' }}" >> .env.local
          
      - name: Build
        run: npm run build
        
      # Add deployment steps here if needed 